name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.0'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build Go application
      run: |
        go build -o main .

    - name: Build Docker image
      run: |
        docker build -t golang .

    - name: Run tests
      run: |
        # Add your test command here
        # For example: go test ./...
        echo "Add your tests here"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Tag and push Docker image
      run: |
        docker tag golang ${{ secrets.DOCKER_HUB_USERNAME }}/golang:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/golang:latest
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing..."
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker aishwar
            fi

            # Pull Docker image and run container
            echo "Pulling Docker image..."
            sudo docker pull takkadapelly/golang:latest
    
           
           # Stop and remove any running container with the same name
           if [ "$(sudo docker ps -a -q -f name=my-app)" ]; then
           echo "Stopping and removing existing container..."
           sudo docker stop my-app || true
           sudo docker rm my-app || true
           fi
 
            
            echo "Running new container..."
            sudo docker run -d -p 8083:8083 --name my-app takkadapelly/golang:latest
          timeout: 30s
          command_timeout: 10m
          debug: false
        